### ISSUE TITLE
add valid remote repo check for <user>@<server>

### ISSUE THREAD

**Issue by nikita-skobov** [nikita-skobov/monorepo-git-tools#20]
there is a function that checks if the user's `remote_repo` is a valid git uri. It is missing a case where a user might have a git uri like:

```
git clone admin@server.local
```
We should check for that via a regex or something.

see the file: `src/split.rs`

The function that needs changing is here: https://github.com/nikita-skobov/monorepo-git-tools/blob/94e825ed8854879d567bb11e7e62d211fbe60ea6/src/split.rs#L538-L541

Also, it would be good to add tests at the bottom of the file to validate that it properly detects valid remote repos.

**Comment by tjtelan** [comment]
Is your intention to support repos only with public DNS? Or just to have a git url that has enough info to clone from? I don't want to assume what is valid in your use-case.

---
If you're looking for a git url validator, I have a crate that does most of the parsing you're doing. I need to add a little bit to support all of the protocols you are checking for. 

https://github.com/tjtelan/git-url-parse-rs

I would be happy to take if you're interested in depending on my crate?

**Comment by nikita-skobov** [comment]
Hi, thanks for taking a look at this issue.
I looked at your git-url parser and it looks good, if you want to take on this issue, could you add a few unit tests to the bottom of `src/split.rs` and test that it returns true for the following git repo urls:

```
../test_repo
..\test_repo
file:///test_repo
https://website.com/username/reponame
https://website.com/username/reponame.git
pi@10.10.10.10:/home/reponame.git
```

if you want to, I have end to end tests located in `test/run_tests.sh` that you can run to verify everything works before submitting your PR. Otherwise, those tests will be ran by GitHub actions when you submit your PR, so you can just see the output of the tests there if you'd like.

Let me know if you have any questions, and thanks again.
